# Generated by Django 3.0.8 on 2020-09-06 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200906_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
    ]
