# Generated by Django 3.0.8 on 2020-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200906_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('opened', 'Opened')], default='opened', max_length=25),
        ),
    ]
